// Mocks generated by Mockito 5.4.4 from annotations
// in max_income/test/widgets/calendar_previous_months_events_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:device_calendar/device_calendar.dart' as _i4;
import 'package:max_income/models/safe_calendar_event.dart' as _i5;
import 'package:max_income/services/calendar_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarService extends _i1.Mock implements _i2.CalendarService {
  MockCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Calendar>> getCalendars() => (super.noSuchMethod(
        Invocation.method(
          #getCalendars,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Calendar>>.value(<_i4.Calendar>[]),
      ) as _i3.Future<List<_i4.Calendar>>);

  @override
  _i3.Future<List<_i5.SafeCalendarEvent>> getCurrentYearEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentYearEvents,
          [],
        ),
        returnValue: _i3.Future<List<_i5.SafeCalendarEvent>>.value(
            <_i5.SafeCalendarEvent>[]),
      ) as _i3.Future<List<_i5.SafeCalendarEvent>>);

  @override
  _i3.Future<List<_i5.SafeCalendarEvent>> getCurrentMonthEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentMonthEvents,
          [],
        ),
        returnValue: _i3.Future<List<_i5.SafeCalendarEvent>>.value(
            <_i5.SafeCalendarEvent>[]),
      ) as _i3.Future<List<_i5.SafeCalendarEvent>>);

  @override
  _i3.Future<List<_i5.SafeCalendarEvent>> getPreviousMonthsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreviousMonthsEvents,
          [],
        ),
        returnValue: _i3.Future<List<_i5.SafeCalendarEvent>>.value(
            <_i5.SafeCalendarEvent>[]),
      ) as _i3.Future<List<_i5.SafeCalendarEvent>>);
}
